security:
    # 1. On dit comment hacher les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    # 2. On dit à Symfony où chercher les utilisateurs (dans la table User, via l'email)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # 3. Les pare-feux (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # A. Le point d'entrée pour récupérer le token
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        # B. La protection du reste de l'API
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    # 4. Les règles d'accès
    access_control:
        # On autorise tout le monde à tenter de se connecter
        - { path: ^/api/login, roles: PUBLIC_ACCESS }

        # NOTE : Pour l'instant on ne bloque pas le reste de l'API pour te laisser
        # accéder à la page API Platform. On bloquera les routes plus tard !
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
